#!/bin/sh
#
# mastodon-worker (sidekiq)
#

# PROVIDE: mastodon_worker
# REQUIRE: LOGIN cleanvar
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable mastodon_worker:
# mastodon_base (string)
#     Set dir to run mastodon
#     Default is "/opt/mastodon"
# mastodon_user (string)
#     Set user to run mastodon
#     Default is "mastodon"
# mastodon_bundle_cmd (string)
#     Set bundle command path.
#     Defalt is "/usr/local/bin/bundle"
# mastodon_worker_enable (bool)
#     Set to "NO" by default.
#     Set it to "YES" to enable mastodon_worker.
#

. /etc/rc.subr

name="mastodon_worker"
rcvar=${name}_enable

load_rc_config $name

extra_commands="status"
start_cmd=${name}_start
stop_cmd=${name}_stop
status_cmd=${name}_status

_log_prefix="/var/log/mastodon"
log_file="${_log_prefix}/${name}.log"
err_log_file="${_log_prefix}/${name}_error.log"

mastodon_bundle_cmd=${mastodon_bundle_cmd:-"/usr/local/bin/bundle"}
mastodon_user=${mastodon_user:-"mastodon"}
rails_env=production

mastodon_worker_enable=${mastodon_worker_enable:-"NO"}
mastodon_worker_base=${mastodon_base:-"/opt/mastodon"}
mastodon_worker_pid=`ps ax | grep sidekiq | grep mastodon | awk '{printf $1" "}'`

mastodon_worker_cmd="${mastodon_bundle_cmd} exec sidekiq -e ${rails_env} 1>>${log_file} 2>>${err_log_file}"


mastodon_worker_start()
{
        su -l ${mastodon_user} -c "touch ${log_file} ${err_log_file}"
        su -l ${mastodon_user} -c "cd ${mastodon_worker_base} && ${mastodon_worker_cmd} &"
        echo "${name} started"
}

mastodon_worker_stop()
{
        if [ "x" == "x${mastodon_worker_pid}" ]; then
                echo "${name} not running?"
        else
                kill ${mastodon_worker_pid}
                echo "${name} stoped"
        fi
}

mastodon_worker_status()
{
        if [ "x" == "x${mastodon_worker_pid}" ]; then
                echo "${name} is not running."
        else
                echo "${name} is running as pid ${mastodon_worker_pid}."
        fi
}

run_rc_command "$1"
