#!/bin/sh
#
# mastodon_web (puma)
#

# PROVIDE: mastodon_web
# REQUIRE: LOGIN cleanvar
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable mastodon_web:
# mastodon_base (string)
#     Set dir to run mastodon
#     Default is "/opt/mastodon"
# mastodon_user (string)
#     Set user to run mastodon
#     Default is "mastodon"
# mastodon_bundle_cmd (string)
#     Set bundle command path.
#     Defalt is "/usr/local/bin/bundle"
# mastodon_web_enable (bool)
#     Set to "NO" by default.
#     Set it to "YES" to enable mastodon_web.
#

. /etc/rc.subr

name="mastodon_web"
rcvar=${name}_enable

load_rc_config $name
: ${mastodon_bundle_cmd:="/usr/loca/bin/bundle"}
: ${mastodon_user:="mastodon"}
: ${mastodon_base:="opt/mastodon"}

piddir="/var/run/mastodon"
pidfile="${piddir}/${name}.pid"

logdir="/var/log/mastodon"
logfile="${logdir}/${name}.log"
err_logfile="${logdir}/${name}_error.log"

procname="ruby"

rails_env="production"

daemon_cmd="/usr/sbin/daemon -u ${mastodon_user} "
mastodon_web_cmd="${mastodon_bundle_cmd} exec puma \
        --environment ${rails_env} \
        --quiet \
        --config config/puma.rb \
        --pidfile ${pidfile} \
        --redirect-stdout ${logfile} \
        --redirect-stderr ${err_logfile} "

start_cmd="${daemon_cmd} ${mastodon_web_cmd}"

export RAILS_ENV="production"
cd ${mastodon_base}


run_rc_command "$1"
