#!/bin/sh
#
# mastodon_web (puma)
#

# PROVIDE: mastodon_web
# REQUIRE: LOGIN cleanvar
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable mastodon_web:
# mastodon_base (string)
#     Set dir to run mastodon
#     Default is "/opt/mastodon"
# mastodon_user (string)
#     Set user to run mastodon
#     Default is "mastodon"
# mastodon_bundle_cmd (string)
#     Set bundle command path.
#     Defalt is "/usr/local/bin/bundle"
# mastodon_web_enable (bool)
#     Set to "NO" by default.
#     Set it to "YES" to enable mastodon_web.
#

. /etc/rc.subr

name="mastodon_web"
rcvar=${name}_enable

load_rc_config $name

extra_commands="status"
start_cmd=${name}_start
stop_cmd=${name}_stop
status_cmd=${name}_status

_log_prefix="/var/log/mastodon"
log_file="${_log_prefix}/${name}.log"
err_log_file="${_log_prefix}/${name}_error.log"

mastodon_bundle_cmd=${mastodon_bundle_cmd:-"/usr/local/bin/bundle"}
mastodon_user=${mastodon_user:-"mastodon"}
rails_env=production

mastodon_web_enable=${mastodon_web_enable:-"NO"}
mastodon_web_base=${mastodon_base:-"/opt/mastodon"}
mastodon_web_pid="/var/run/mastodon/puma.pid"
mastodon_web_cmd="${mastodon_bundle_cmd} exec puma \
        --environment ${rails_env} \
        --quiet \
        --config config/puma.rb \
        --pidfile ${mastodon_web_pid} \
        --redirect-stdout ${log_file} \
        --redirect-stderr ${err_log_file} \
        --daemon "

mastodon_web_start()
{
        su -l ${mastodon_user} -c "touch ${log_file} ${err_log_file}"
        su -l ${mastodon_user} -c "cd ${mastodon_web_base} &&  ${mastodon_web_cmd}"

        echo "${name} started"
}

mastodon_web_stop()
{
        if [ "x" == "x`cat ${mastodon_web_pid}`" ]; then
                echo "${name} not running?"
        else
                kill -9 ${mastodon_web_pid}
                rm ${mastodon_web_pid}
                echo "${name} stoped"
        fi
}

mastodon_web_status()
{
        if [ "x" == "x`cat ${mastodon_web_pid}`" ]; then
                echo "${name} is not running. pid: `cat ${mastodon_web_pid}`"
        else
                echo "${name} is running as pid `cat ${mastodon_web_pid}`."
        fi
}

run_rc_command "$1"
