#!/bin/sh
#
# mastodon_stream (node.js)
#

# PROVIDE: mastodon_stream
# REQUIRE: LOGIN cleanvar
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable mastodon_stream:
# mastodon_base (string)
#     Set dir to run mastodon
#     Default is "/opt/mastodon"
# mastodon_user (string)
#     Set user to run mastodon
#     Default is "mastodon"
# mastodon_stream_enable (bool)
#     Set to "NO" by default.
#     Set it to "YES" to enable mastodon_stream.
#

. /etc/rc.subr

name="mastodon_stream"
rcvar=${name}_enable

load_rc_config $name
: ${mastodon_bundle_cmd:="/usr/local/bin/bundle"}
: ${mastodon_user:="mastodon"}
: ${mastodon_base:="/ope/mastodon"}

piddir="/var/run/mastodon"
pidfile="${piddir}/${name}.pid"

logdir="/var/log/mastodon"
logfile="${logdir}/${name}.log"
err_logfile="${logdir}/${name}_error.log"

procname="node"

PATH=${PATH}:/usr/local/bin
export NODE_ENV=production
export STREAMING_CLUSTER_NUM=1

daemon_cmd="/usr/sbin/daemon -u ${mastodon_user} -p ${pidfile} -m 2 -o ${err_logfile}"
start_cmd="${daemon_cmd} node ./streaming/index.js"

cd ${mastodon_base}


run_rc_command "$1"
