#!/bin/sh
#
# mastodon-worker (sidekiq)
#

# PROVIDE: mastodon_worker
# REQUIRE: LOGIN cleanvar
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable mastodon_worker:
# mastodon_base (string)
#     Set dir to run mastodon
#     Default is "/opt/mastodon"
# mastodon_user (string)
#     Set user to run mastodon
#     Default is "mastodon"
# mastodon_bundle_cmd (string)
#     Set bundle command path.
#     Defalt is "/usr/local/bin/bundle"
# mastodon_worker_enable (bool)
#     Set to "NO" by default.
#     Set it to "YES" to enable mastodon_worker.
#

. /etc/rc.subr

name="mastodon_worker"
rcvar=${name}_enable

load_rc_config $name
: ${mastodon_bundle_cmd:="/usr/local/bin/bundle"}
: ${mastodon_user:="mastodon"}
: ${mastodon_base:="/opt/mastodon"}

piddir="/var/run/mastodon"
pidfile="${piddir}/${name}.pid"

logdir="/var/log/mastodon"
logfile="${logdir}/${name}.log"
err_logfile="${logdir}/${name}_error.log"

procname="ruby"

export RAILS_ENV=production
export RAILS_LOG_LEVEL=warn
export DB_POOL=25
export MALLOC_ARENA_MAX=2

daemon_cmd="/usr/sbin/daemon -u ${mastodon_user} -p ${pidfile} -m 2 -o ${err_logfile} "
start_cmd="${daemon_cmd} ${mastodon_bundle_cmd} exec sidekiq  > ${logfile}"

cd $mastodon_base

run_rc_command "$1"
